version: '3.9'

services:
  scheduleproject:
    container_name: scheduleproject
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./scheduleproject:/scheduleproject
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./scheduleproject/dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./scheduleproject/dotenv_files/.env